### ISSUE TITLE
Installation of netbird fails on Fedora Atomic-based Immutable Systems

### ISSUE THREAD

**Issue by M0Rf30** [netbirdio/netbird#1634] opened 2024-02-27 16:19 UTC
**Describe the problem**

following the installation details for rpm lead to a failing postinstall execution

The error reported is
```
Post Install of an clean install
open /etc/init.d/netbird: no such file or directory
Error: open /etc/init.d/netbird: no such file or directory
"service" failed: exec: "service": executable file not found in $PATH
Error: "service" failed: exec: "service": executable file not found in $PATH
```
as suggested by the package manager you can view this error with the command
`journalctl -t 'rpm-ostree(netbird.post)'`

**To Reproduce**

1. add the repo under repos.d folder
2. do an `rpm-ostree update` (the repo is evaluated in the right manner)
3. do an `rpm-ostree install netbird`

**Expected behavior**

**NetBird version**

`from 0.25.8 to 0.26.0`

**Comment by mlsmaycon** [comment] 2024-03-04 09:57
@M0Rf30 can you share your fedora version?

**Comment by jkrogers9862** [comment] 2024-04-25 17:20
Is there any word on this issue? It is still persistent in 2.7.3 on Fedora Silverblue 39.

**Comment by jkrogers9862** [comment] 2024-06-10 05:17
I have noted that when I tried to install qemu-kvm and Virtualization tools on Fedora Silverblue 40, this issue appears. I have also had this issue with coreos and fedora iot. This issue continues to be present in netbird 0.27.10. I have been using  use the docker version on systems where this is happening. Please take a new look at this issue.

**Comment by jkrogers9862** [comment] 2024-08-21 02:47
Is there no fix or workaround discovered for this yet? Why does netbird to install on immutable systems when virtualization tools are installed? The cause give is about as vague as it gets. The same thing happens when just installing network-scripts. It is really frustrating as I want to use native nebird rather than docker because docker seems to lose a lot of functionality and is very unstable.
![Screenshot_20240821_114421](https://github.com/user-attachments/assets/3a732293-0450-4786-be61-3a4ed41144af)
![Screenshot_20240821_114145](https://github.com/user-attachments/assets/9e68b578-2a75-4d64-a9e8-d150cd9d50cb)
![Screenshot_20240821_113837](https://github.com/user-attachments/assets/a85b9977-8f45-4592-98db-c0de8d85e8c2)

**Comment by TobinHall** [comment] 2024-08-29 07:18
I have just had a brief look at this. It seems that the netbird installer will try to invoke service install which uses the service installer from [github.com/kardianos/service](github.com/kardianos/service). 

For coreos it should determine that the system type is systemd but I believe it does not pass [these](https://github.com/kardianos/service/blob/becf2eb62b83ed01f5e782cb8da7bb739ded2bb5/service_systemd_linux.go#L22-L45) tests. 

I am not familiar enough with the way rpm-ostree works to understand why this fails or how to work around it. But this issue may need to be fixed in [github.com/kardianos/service](github.com/kardianos/service).

**Comment by jkrogers9862** [comment] 2024-08-31 13:22
> For coreos it should determine that the system type is systemd but I believe it does not pass [these](https://github.com/kardianos/service/blob/becf2eb62b83ed01f5e782cb8da7bb739ded2bb5/service_systemd_linux.go#L22-L45) tests.


I'm not sure I follow. I am not familiar with the service in question but given your determination that does not pass these test is true, why is it it only fails when installing network and virtualization related packages on Silverblue (and other immutable desktops like Silverblue). In particular, it fails with `libvirt` but I even narrowed it down to failing with just installing `network-scripts` (which is tiny, a few Kbs) on top of `netbird` on a base image Silverblue (Kinoite). Silverblue being much closer to a traditional desktop is a lot less specialized and fine tuned than CoreOS. I can understand why CoreOS might fail as it is probably has a lot of these packages in the base image. But Silverblue does not which is why `netbird` installs fine until you try to install `libvirt` or `network-scripts`.

Can you explain what led you to your conclusion? What steps you took? I can fine no useful information in the logs.

**Closed** 2024-09-04 17:22 UTC
Labels: bug, client

**Comment by jkrogers9862** [comment] 2024-09-09 23:39
As of today, I attempted to install Netbird 0.29.0 and the same error still comes up as before, so either this is still a problem or there were actually two problems that caused the same error.

**Comment by M0Rf30** [comment] 2024-09-10 10:52
> As of today, I attempted to install Netbird 0.29.0 with `'libvirt virt-manager network-scripts'` and the same error still comes up as before, so either this is still a problem or there were actually two problems that caused the same error. @bcmmbaga @M0Rf30

I finally managed to do better debugging

https://github.com/netbirdio/service/pull/3
