### ISSUE TITLE
Feature: Exit nodes

### ISSUE THREAD

**Issue by giezi** [netbirdio/netbird#723] opened 2023-03-05 19:53 UTC
**Describe the solution you'd like**
It would be great if you could implement exit nodes like Tailscale, which can be selected in the client.
https://tailscale.com/kb/1103/exit-nodes/

Many thanks for considering this :)

**Comment by lorenzo95** [comment] 2023-05-04 21:09
Agree. It's a bit odd that this is missing. The network routes section won't let you add a route smaller than a /7

**Comment by mrbluecoat** [comment] 2023-06-01 04:15
duplicate of #289

**Comment by mlsmaycon** [comment] 2023-06-16 06:45
Closing duplicate

**Closed by mlsmaycon** 2023-06-16 06:45 UTC

**Comment by thehoff** [comment] 2023-09-19 14:47
you say this is a duplicate of #289 and that brings me to #723 and they are both closed and netbird still wont allow anything larger than a /7. 
the use of a 0.0.0.0/0 route especially with mobile devices might even solve the bug you have in the android client on #858 ?

**Comment by tbleiker** [comment] 2023-10-05 08:37
Any update on this? I am evaluating a few solutions and I like netbird a lot. However, I need this functionality.

**Comment by tiagogbarbosa** [comment] 2023-12-12 01:28
Any updates on this?

**Comment by EngEryx** [comment] 2023-12-18 10:08
Having an Exit node can come in handy..

**Comment by B08Z** [comment] 2024-01-08 21:10
Is this a planned feature. It's the only thing stopping me using netbird as my primary (and only) VPN solution.

**Comment by svardie** [comment] 2024-04-05 00:52
Any news on when exit node feature will come to Android/iOS clients? Looks like this is only feature, that keeping us from switching to NetBird.
