### ISSUE TITLE
Management Server is limited to 100 simultaneous peers

### ISSUE THREAD

**Issue by TSJasonH** [netbirdio/netbird#1824] opened 2024-04-10 15:13 UTC
**Describe the problem**

After 100 peers have connected the management server stops letting more connect. 

**To Reproduce**

1. Self-Host
2. Permit more than 100 peers
3. Have them all connect
4. after 100 no more get a connection

**Expected behavior**

A more realistic limit

**Are you using NetBird Cloud?**

Self-Hosted

**NetBird version**

0.27.1 (management)

**Additional context**

For any user beyond the limit, the management log shows these WARN entries: 
```
"{"log":"2024-04-10T12:50:02Z WARN management/server/grpcserver.go:376: failed logging in peer Ij6aLkfZU7qzUOgfzTAZMaaLNAOGsow2SDmdP+8Rxig=\n","stream
":"stderr","time":"2024-04-10T12:50:02.614030981Z"}"
```

While chatting in the slack my colleague found this reference, which _seems that it may be related_. Can this be made to a customize-able setting that defaults to 100 if not otherwise specified? 

https://github.com/netbirdio/netbird/blob/3ed2f08f3c5dd930a598a26f24cf028807816486/management/server/updatechannel.go#L13

`const channelBufferSize = 100`

https://github.com/netbirdio/netbird/blob/main/management/server/updatechannel.go#L83-L85

> 	// mbragin: todo shouldn't it be more? or configurable?
> 	channel := make(chan *UpdateMessage, channelBufferSize)
> 	p.peerChannels[peerID] = channel

**Comment by pappz** [comment] 2024-04-10 15:22
Hello!
Could you set trace log level for the server and collect the relevant part of the new logs? You can set it with the `"--log-level" , "trace" ` command parameters.

**Comment by bravosierrasierra** [comment] 2024-06-04 20:12
@pappz Same problem on 0.27.10. Changing const channelBufferSize to 1000 modifies maximum peers to 1000. This is strange, but works.

**Comment by mlsmaycon** [comment] 2024-06-04 20:18
Hello @bravosierrasierra the buffer size is a queue that indicates the number of messages to send a specific peer in the netbird network.

So you can have hundreds of thousands of nodes and each one of them will have a max of 100 messages that can be queued.

It seems like you are facing another issue with the deployment which is causing these messages.

Can you share the all management logs? And confirm if you have JWT group sync enabled?

**Comment by akastav** [comment] 2024-06-05 06:00
I confirm that I have encountered a similar problem. It is also described here https://github.com/netbirdio/netbird/issues/1782

After adding 101 participants to 1 group, errors occur and randomly 1 of the participants is not announced. Sometimes - this participant is a router. I corrected it https://github.com/netbirdio/netbird/blob/main/management/server/updatechannel.go#L13 increasing the value to 1000 and the problem is gone

**Comment by mlsmaycon** [comment] 2024-06-05 06:53
Hi @akastav can you share if you have JWT group sync enabled?

**Comment by bravosierrasierra** [comment] 2024-06-05 07:32
> Hi @akastav can you share if you have JWT group sync enabled?

yes, we use groups from JWT/Keycloak

**Comment by mlsmaycon** [comment] 2024-06-05 07:37
Ok, this is probably the main issue. There is a bug to be fixed in our roadmap which causes lot's of group reconfiguration. You can check that by the number of duplicated group events you have in the activity view.

**Comment by bravosierrasierra** [comment] 2024-06-05 08:07
> Ok, this is probably the main issue. There is a bug to be fixed in our roadmap which causes lot's of group reconfiguration. You can check that by the number of duplicated group events you have in the activity view.

But why increasing channelBufferSize solve problem?
Does this bug about JWT groups from roadmap have a link we can follow?

**Comment by mlsmaycon** [comment] 2024-06-06 12:39
@bravosierrasierra @akastav, what are your IDP providers?

**Comment by bravosierrasierra** [comment] 2024-06-06 12:45
@mlsmaycon we are both use different keycloak-s

**Comment by mlsmaycon** [comment] 2024-06-07 09:18
We found the root cause of the issue and we are working on a fix.

**Comment by mlsmaycon** [comment] 2024-06-14 10:02
Hey folks, the PR has been merged and will be in our next release.

**Comment by mlsmaycon** [comment] 2024-07-03 08:58
Hey folks, have you tested? Should we close this issue?

**Comment by TSJasonH** [comment] 2024-07-03 12:47
I'll be doing the upgrade this Saturday.

**Comment by TSJasonH** [comment] 2024-07-06 11:15
I finished my upgrades to 0.28.4 and re-enabled JWT sync. I can confirm that I'm not seeing multiple repeating group inserts for users any longer. I believe this can be closed now. Thanks!!

**Comment by mlsmaycon** [comment] 2024-07-08 12:22
That's excellent; thanks, @TSJasonH, for double checking. I am closing this now.

**Closed by mlsmaycon** 2024-07-08 12:22 UTC
Labels: management-service

**Comment by lonnietc** [comment] 2025-02-21 19:00
Hello All,

Is the latest netbird self-hosting still limited by default to 100?

Thanks

**Comment by lixmal** [comment] 2025-02-21 19:06
@lonnietc There has never been a limit, this was a bug.

**Comment by lonnietc** [comment] 2025-02-21 19:20
@lixmal Thanks so very much for this wonderful information.

My project is to effectively build a Netbird-type competitor to the Yggdrasil VPN to have an ecosystem that is effectively a VPN based Internet plus built-in services and I am trying to get an idea as to how Netbird might function at massive scale.  I also looked into many other possible solutions like Tailscale, ZeroTier, and others, but REALLY like the potential of Netbird and it if can massively scale then that would be a great starting point as the core network.

Of course, I still have to investigate how to make it truly decentralized to include management, signals, and relays, but that is later.

Thanks again and have a great day, my friend.
