### ISSUE TITLE
ios app private dns not work

### ISSUE THREAD

**Issue by rookie-man-fack** [netbirdio/netbird#1501] opened 2024-01-28 08:05 UTC
The private DNS service is working properly on Mac OS and Linux, and browsers and other applications can parse DNS records normally, but iOS cannot parse private DNS records

**Comment by rookie-man-fack** [comment] 2024-01-28 08:20
![IMG_1539](https://github.com/netbirdio/netbird/assets/110986345/70ff7e76-6d7b-439e-9746-9d7773ad9f83)
![IMG_1540](https://github.com/netbirdio/netbird/assets/110986345/ced7771f-f560-46b5-8ccb-8533af7e7d36）

**Comment by rookie-man-fack** [comment] 2024-01-28 08:21
![IMG_1540](https://github.com/netbirdio/netbird/assets/110986345/217ac81b-c9a5-47b2-8f0f-ffb1835c44cf)
![IMG_1539](https://github.com/netbirdio/netbird/assets/110986345/432f7705-d955-4c3e-b42d-ef6cc126c897)

**Comment by rookie-man-fack** [comment] 2024-01-28 08:22
![IMG_1541](https://github.com/netbirdio/netbird/assets/110986345/9502c71d-eeca-4d1f-87e7-bdc108365061)
![IMG_1539](https://github.com/netbirdio/netbird/assets/110986345/cba3fe5e-796e-4b33-a18b-6e4294afdc38)

**Comment by ykorzikowski** [comment] 2024-02-01 18:16
I don't know if this is the same issue, but I notice with the latest iOS / Netbird App, that the dns setting is not setup correct anymore. 

<img width="1215" alt="Screenshot 2024-02-01 at 19 15 31" src="https://github.com/netbirdio/netbird/assets/20556547/d9ca14c8-eb03-4d8f-b83c-e66810fc0740">

I can ping my dns server from the iphone, but it still uses the dhcp one provided by my local network or the mobile provider one when on 4G/5G.

**Comment by rookie-man-fack** [comment] 2024-02-02 06:49
> 我不知道这是否是同一个问题，但我注意到最新的iOS/Netbird应用程序的dns设置不再正确设置。
> 
> <img alt="屏幕截图 2024-02-01 at 19 15 31" width="1215" src="https://private-user-images.githubusercontent.com/20556547/301604724-d9ca14c8-eb03-4d8f-b83c-e66810fc0740.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTY0NDgsIm5iZiI6MTcwNjg1NjE0OCwicGF0aCI6Ii8yMDU1NjU0Ny8zMDE2MDQ3MjQtZDljYTE0YzgtZWIwMy00ZDhmLWI4M2MtZTY2ODEwZmMwNzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAyVDA2NDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNWI3N2I2NTMwODBhM2JlMmNmOGNkZWMyNTkxNDEzNGFlM2M2NmI1OWRkOGEyZjk0NjhlOWJmZjVjMDU3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g1ex8brcICYVkNj0n56il8vunm_PWST5UgepycL-0-U">
> 我可以从iphoneping我的dns服务器，但它仍然使用我的本地网络提供的dhcp服务器，或者在4G/5G时使用移动提供商提供的dhcp服务器。运行最新的iOS17.3，并使用最新的netbird应用程序0.0.2。

Yes, the packet capture shows that the iOS client does not smuggle DNS routes. This should be the system mechanism of iOS.

**Comment by bcmmbaga** [comment] 2024-02-13 11:04
Hello @rookie-man-fack, we're unable to reproduce the issue on our end. It's important to note that not all terminal clients behaves well in iOS. I suggest testing the name resolution by accessing a web server connected via Netbird through a browser on your iOS device.

**Comment by Benricheson101** [comment] 2024-02-14 19:49
I am having the same issue. Adding a DNS Nameserver with an IP accessible through a Network Route in Netbird works as expected on the desktop client, but no DNS queries seem to resolve on iOS.

**Comment by jacac** [comment] 2024-02-14 22:40
Tests on a iPad were successful. On a iPhone we could not get DNS working. I've tried both with `Match domains` and `All`.

**Comment by alexstrzelecki** [comment] 2024-02-15 07:21
Can confirm that iOS (iPhone) will not resolve any DNS via the selected nameserver while desktop clients do so without issue via the same network route. (Linux / MacOS).

**Comment by mlsmaycon** [comment] 2024-02-15 15:25
Hello folks, we are working on a fix for this issue and we will push a release soon.

**Comment by mlsmaycon** [comment] 2024-02-16 18:39
the fix is under review by Apple, we should have the version over the weekend or early next week.

**Comment by mlsmaycon** [comment] 2024-02-17 22:49
The release is live. Let us know if you continue to face issues.

**Closed by mlsmaycon** 2024-02-17 22:49 UTC
Labels: triage

**Comment by rookie-man-fack** [comment] 2024-02-18 08:51
iOS is updated to the latest version, but the internal DNS still cannot be resolved. For packet capture and observation, the DNS assigned by dhcp is still used. (Linux / MacOS)resolves normally.

**Comment by jacac** [comment] 2024-02-20 16:45
Update to version 0.0.3 and private DNS is working now. Thank you.

**Comment by snibbo71** [comment] 2024-03-19 18:00
I have discovered, perhaps by accident, that at least in my setup, if you're wanting to use a private DNS relay then you MUST use a server that is running Netbird.

In my case, my private DNS server is on Openwrt and controls various local DNS entries. My NetBird network router though is a Proxmox LXC and none of the individual machines in my LAN run Netbird.

I had set my DNS server to be 192.168.0.1 (the LAN address of my OpenWRT router). This failed with a timeout and no amount of checking static routes managed to fix it. This seems to be because, for IOS at least on my configuration, the DNS Server on the client is set to 100.xxx.255.254 which is not pingable from the OpenWRT router. So the DNS request reaches the router, but its answer doesn't make it back to the client.

Setting up a DNS Proxy on the LXC and setting my Netbird DNS Server Address to be the LXC LAN address solves the problem and I can use private DNS.

I'm not sure if this is expected behaviour. For additional context here, I am using an LTE connection, which appears to be CGNATted and the client is being relayed.

Also, yes, I could use Netbird directly on OpenWRT which I have done, but the CPU load, even using kernel wireguard, is prohibitive, versus barely noticeable on the LXC, though presumably this is why the connection is relayed at present.
