### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dillfrescott** [netbirdio/netbird#852] opened 2023-05-12 19:23 UTC
Is there a way for a peer to disable the ssh ability?

**Comment by oskardotglobal** [comment] 2023-05-15 18:28
You mean the ability for a peer to connect via SSH? AFAIK not, but you could restrict access entirely using ACL or try to block the connection from that IP on the port via iptables

**Comment by dillfrescott** [comment] 2023-09-12 00:31
Is there a way to do this officially yet?

**Comment by braginini** [comment] 2023-09-12 04:22
Hey @dillfrescott 

I think that this won't be hard to add as a client parameter. I will check this next week.

**Comment by tjarbo** [comment] 2023-11-12 17:50
Would suggest to close this as duplicate of #509, and to continue discussion there.

**Comment by mlsmaycon** [comment] 2023-11-14 08:44
duplicate of #509

**Closed by mlsmaycon** 2023-11-14 08:44 UTC
